### ISSUE TITLE
Enemy AI Y rotation bug

### ISSUE THREAD

**Issue by Division13studio** [eduhaidu/Go-To-Hell#4]
Enemy AI looks up if player jumps or gets above him and if he dies his corpse is set in an unnatural and distracting position - ex: head first into the floor - fix by limiting rotation and making sure rotation is correct if enemy is killed by weapon and  dies without gore.
![image](https://github.com/eduhaidu/Go-To-Hell/assets/115345119/7e82bd82-0e42-4a80-bc96-ae752f373789)

**Comment by eduhaidu** [comment]
The issue was fixed by changing the euler angles of the enemy transform
